In [33]:
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd

In [48]:
def hollysCrawling(pageNum):
  store_name = []
  store_address = []
  store_tel = []

  for n in range(0, pageNum):
    hollysURL = 'https://www.hollys.co.kr/store/korea/korStore2.do?pageNo=%d&sido=&gugun=&store=' % (n + 1)
    hollysHTML = urllib.request.urlopen(hollysURL).read()

    hollysSoap = BeautifulSoup(hollysHTML, 'html.parser')
    hollysTBody = hollysSoap.find('tbody')
    hollysTR = hollysTBody.find_all('tr')

    for tr in hollysTR:
      hollysTD = tr.find_all('td')
      store_name.append(hollysTD[1].string)
      store_address.append(hollysTD[3].string)
      store_tel.append(hollysTD[5].string)

  Hollys_dic = {'매장이름':store_name, '주소':store_address, '전화번호':store_tel}
  Hollys_store = pd.DataFrame(Hollys_dic)

  return Hollys_store

In [50]:
Hollys_store = hollysCrawling(54)
Hollys_store

         매장이름                                                주소          전화번호
0     건대일감호수점                  서울특별시 광진구 아차산로39길 38-6 (자양동) 할리스   02-456-6627
1    부천순천향병원점                   경기도 부천시 조마루로 170(중동) 본관 지하 1층 .             .
2      전주시네마점        전라북도 전주시 완산구 전주객사3길 67 (고사동, 전주시네마타운) 1~2층  063-232-9448
3       천안신부점              충청남도 천안시 동남구 만남로 26 (신부동, 대영빌딩) 4~5층  041-566-5085
4    목동삼성쉐르빌점  서울특별시 양천구 목동동로 189 (신정동, 삼성쉐르빌1) 1층 101,102,103호  02-2652-2030
..        ...                                               ...           ...
529       신림점                               서울특별시 관악구 신림로 353-1   02-877-0019
530      태평로점        서울특별시 중구 세종대로 64, 해남빌딩 1층 (태평로2가 70-5) 할리스   02-755-7795
531      이태원점                               서울특별시 용산구  이태원로 179   02-749-8752
532    부산서면본점  부산광역시 부산진구 동천로 73, DS타워 1~2층 (부전동 부전동 169-1) 할리스  051-819-9117
533       신촌점                서울특별시 서대문구 연세로 34 (창천동 31-12)  할리스   02-393-2004

[534 rows x 3 columns]

In [51]:
Hollys_store.to_excel('hollys_coffee.xlsx', sheet_name='shop')